### ISSUE TITLE
Failed assertion: line 23 pos 14: 'url != [   +2 ms] I/flutter (20089): null': is not true.

### ISSUE THREAD

**Issue by therichiekumar** [mitesh77/Best-Flutter-UI-Templates#11] opened 2019-10-06 12:19 UTC
[+134376 ms] I/flutter (20089): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[   +3 ms] I/flutter (20089): The following assertion was thrown building:
[   +1 ms] I/flutter (20089): 'package:flutter/src/painting/_network_image_io.dart': Failed assertion: line 23 pos 14: 'url !=
[   +2 ms] I/flutter (20089): null': is not true.
[   +1 ms] I/flutter (20089):
[   +1 ms] I/flutter (20089): Either the assertion indicates an error in the framework itself, or we should provide substantially
[   +2 ms] I/flutter (20089): more information in this error message to help you determine and fix the underlying cause.
[   +1 ms] I/flutter (20089): In either case, please report this assertion by filing a bug on GitHub:
[   +1 ms] I/flutter (20089):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[   +1 ms] I/flutter (20089):
[   +1 ms] I/flutter (20089): When the exception was thrown, this was the stack:
[   +1 ms] I/flutter (20089): #2      new NetworkImage (package:flutter/src/painting/_network_image_io.dart:23:14)
[   +1 ms] I/flutter (20089): #3      _OurTeamState.build.<anonymous closure>.<anonymous closure> (package:charaka/our_team.dart:100:33)
[   +2 ms] I/flutter (20089): #4      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:448:15)
[   +1 ms] I/flutter (20089): #5      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1185:67)
[   +2 ms] I/flutter (20089): #6      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:137:29)
[   +1 ms] I/flutter (20089): #7      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1185:26)
[        ] I/flutter (20089): #8      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1198:55)
[        ] I/flutter (20089): #9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2321:19)
[        ] I/flutter (20089): #10     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1191:11)
[   +1 ms] I/flutter (20089): #11     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure>
(package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
[   +1 ms] I/flutter (20089): #12     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1797:58)
[   +1 ms] I/flutter (20089): #13     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:875:15)
[        ] I/flutter (20089): #14     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1797:13)
[   +1 ms] I/flutter (20089): #15     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
[   +1 ms] I/flutter (20089): #16     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:489:5)
[        ] I/flutter (20089): #17     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:195:19)
[        ] I/flutter (20089): #18     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:238:19)
[        ] I/flutter (20089): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (20089): #20     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
[        ] I/flutter (20089): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (20089): #22     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
[        ] I/flutter (20089): #23     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1355:12)
[        ] I/flutter (20089): #24     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1273:20)
[        ] I/flutter (20089): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (20089): #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (20089): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (20089): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (20089): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (20089): #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (20089): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (20089): #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (20089): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (20089): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (20089): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (20089): #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (20089): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (20089): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (20089): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (20089): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[   +1 ms] I/flutter (20089): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (20089): #42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (20089): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (20089): #44     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:161:11)
[        ] I/flutter (20089): #45     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
[        ] I/flutter (20089): #46     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:231:7)
[        ] I/flutter (20089): #47     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:392:14)
[        ] I/flutter (20089): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (20089): #49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (20089): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (20089): #51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (20089): #52     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
[   +1 ms] I/flutter (20089): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (20089): #54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (20089): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (20089): #56     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
[        ] I/flutter (20089): #57     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1578:7)
[        ] I/flutter (20089): #58     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
[        ] I/flutter (20089): #59     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:340:19)
[        ] I/flutter (20089): #60     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:776:13)
[        ] I/flutter (20089): #61     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:279:5)
[        ] I/flutter (20089): #62     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1040:15)
[        ] I/flutter (20089): #63     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:982:9)
[        ] I/flutter (20089): #64     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:898:5)
[        ] I/flutter (20089): #68     _invoke (dart:ui/hooks.dart:249:10)
[        ] I/flutter (20089): #69     _drawFrame (dart:ui/hooks.dart:207:3)
[        ] I/flutter (20089): (elided 5 frames from class _AssertionError and package dart:async)
[        ] I/flutter (20089): ════════════════════════════════════════════════════════════════════════════════════════════════════

Device- Real (Xiomi K20 Pro)

After open the drawer nothing works,
Invite friends's screen share button shows this error

**Comment by mitesh77** [comment] 2019-11-23 14:59
please try again and check (this is a stable channel), (you can re-clon project please and try)

**Comment by therichiekumar** [comment] 2019-11-23 18:11
Hello @mitesh77 , I tried but nothing is changed.

**Comment by anggun21** [comment] 2020-03-11 08:45
Duplicate of #30

**Comment by pd0h** [comment] 2021-03-02 07:41
Y

**Comment by mitesh77** [comment] 2021-05-19 06:12
I am not sure about it

**Closed by mitesh77** 2021-05-19 06:12 UTC

**Comment by baimamboukar** [comment] 2021-07-04 12:00
make sure your device is connected to internet.......
