### ISSUE TITLE
after open drawer and end drawer, the button not working

### ISSUE THREAD

**Issue by rachidev84** [mitesh77/Best-Flutter-UI-Templates#40] opened 2020-05-23 18:52 UTC
I use xiomi new device version android 9, 
the drawer still open and close , and the touch button of main screen not working
that happen if I open drawer, if not the button on main screen works

**Comment by cv692001** [comment] 2020-08-21 08:04
Hey @rachidev84  , I am interested i solving this issue can you please elaborate :)

**Comment by leithhobson** [comment] 2020-08-25 14:51
@cv692001 

Sorry, I will come back to elaborate later, but basically, once you have opened the drawer once, clicking anywhere on the screen will only open/close the drawer, effectively disabling the entire content of the screen.

As I said, I'm in a rush now, and will update this comment ASAP

**Comment by leithhobson** [comment] 2020-08-26 00:08
> Hey @rachidev84 , I am interested i solving this issue can you please elaborate :)

@cv692001 as promised, here is my follow up.

Hopefully the issue is visible below, effectively, once you trigger the drawer a single time, it is as though it is on top of the screen, and any action on screen (other than selecting an item in the drawer) will result in opening/closing the drawer, regardless of what you are trying to select.

Look forward to any fix you are able to create. - I'm a complete flutter beginner

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33805066/91239805-acb9c380-e740-11ea-8ed9-7f2b3ffe5495.gif)

**Comment by leithhobson** [comment] 2020-08-27 07:00
This issue was resolved in fd483092033e496c981a8a038429790289175c93 @mitesh77 you can close it

**Comment by mitesh77** [comment] 2020-08-27 07:15
@leithhobson  thanks

**Closed by mitesh77** 2020-08-27 07:15 UTC
